"""empty message

Revision ID: e59bb5f6fe65
Revises: 6b040999c64f
Create Date: 2025-11-03 21:41:00.806160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e59bb5f6fe65'
down_revision = '6b040999c64f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('vehicle_class', sa.String(length=120), nullable=True),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('cost_in_credits', sa.String(length=120), nullable=True),
    sa.Column('length', sa.String(length=120), nullable=True),
    sa.Column('crew', sa.String(length=120), nullable=True),
    sa.Column('passengers', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skin_color', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('eye_color', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))
        batch_op.alter_column('height',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('mass',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('hair_color',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'vehicle', ['vehicle_id'], ['id'])

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rotation_period', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('orbital_period', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('gravity', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('population', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))
        batch_op.alter_column('diameter',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('diameter',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('description')
        batch_op.drop_column('population')
        batch_op.drop_column('gravity')
        batch_op.drop_column('orbital_period')
        batch_op.drop_column('rotation_period')

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vehicle_id')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('hair_color',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('mass',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('height',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('description')
        batch_op.drop_column('gender')
        batch_op.drop_column('eye_color')
        batch_op.drop_column('skin_color')

    op.drop_table('vehicle')
    # ### end Alembic commands ###
